### ISSUE TITLE
reserved claim exp fails validation

### ISSUE THREAD

**Issue by stephenbeauchamp** [AidanDai/node.jwt#1]
Hi, thanks for a great JWT library. I was using it for a token with the reserved claim 'exp' set to indicate the expiry date.

It refused to validate, even if I had just created it on the line above the validation. I tracked it down to the date comparison being done. I went off the RFC 7519 spec for the time storage in seconds (end of section 2): https://tools.ietf.org/html/rfc7519#page-9

I think lib/jwt.js line: 150 should read

`   // Support for exp claims, and so on`
`    if (payload.exp && !isNaN(parseInt(payload.exp,10)) && Date.now() > (new Date(parseInt(payload.exp,10)*1000)) ) {`
`      errorMap['007'].error = new Error(errorMap['007'].message)`
`      return errorMap['007']`
`    }`

**Comment by AidanDai** [comment]
I'm sorry to see your `issue` now. After reading these two statements about `exp`, I felt I had made a serious mistake. Thank you very much for pointing out the mistake in time.

- [https://tools.ietf.org/html/rfc7519#page-9](https://tools.ietf.org/html/rfc7519#page-9)
- [http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#rfc.section.4.1.4](http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#rfc.section.4.1.4)

I have temporarily repaired this `bug` (as follows). If you have better advice, please just direct `pull`

```javascript
if (payload.exp) {
  let exp = Date.parse(payload.exp)

  if (isNaN(exp)) {
    errorMap['008'].error = new Error(errorMap['008'].message)
    return errorMap['008']
  }

  if (Date.now() > exp) {
    errorMap['007'].error = new Error(errorMap['007'].message)
    return errorMap['007']
  }
}
```
