### ISSUE TITLE
Code 006 empty message

### ISSUE THREAD

**Issue by jdarling** [AidanDai/node.jwt#5]
Looks like code 006 never quite got completed in jwt.js it's returning an empty message string

```
{ code: '006', message: '', error: null }
```

Looking at the tests I was able to figure out that that should say 'Unvalid public secret for rsa verify, signature verification failed'

I'm guessing that that means that the cert is invalid.

**Comment by stephenbeauchamp** [comment]
I think each verification routine needs to throw an error if it fails to match.... 

Aidan, if you agree, I'm happy to correct and provide a PR.

`function hmacVerify (input, algorithm, secret, signature) {
  try {
    **if ( signature !== hmacSign(input, algorithm, secret) ) {
      throw new Error("Token cannot be verified. Supplied signature doesn't match message signature.")
    }
    return true**
  } catch (e) {
    errorMap['006'].message = 'Exception error in hamc verify, signature verification failed'
    errorMap['006'].error = e
    return false
  }
}`

**Comment by AidanDai** [comment]
@demoaddr I am sorry to reply you so late. I will repair this bug and publish next version
@stephenbeauchamp Of course, I am very happy for your PR, but I must sure this's correctly.

thanks very much, last but import, this is awesome some people to contribute this package.

**Comment by AidanDai** [comment]
@jdarling 
@stephenbeauchamp 

The bug is fixed, see [https://github.com/AidanDai/node.jwt/commit/b540e3e8e38b7b3685e815e1d6770a3ab17a0ec2](https://github.com/AidanDai/node.jwt/commit/b540e3e8e38b7b3685e815e1d6770a3ab17a0ec2) for more detail. welcome to discuss with me.

**Comment by jdarling** [comment]
Awesome, thanks.  Sorry I hadn't followed up on this, been swamped with other things taking my attention.

**Comment by AidanDai** [comment]
@jdarling No thanks!

 I understand that everyone to be busy. if you find other problem, welcome discuss anytime.
